const CONFIG = {
  SUPABASE_URL: 'https://tjjmkwffbbcuztclmfap.supabase.co',
  SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqam1rd2ZmYmJjdXp0Y2xtZmFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODAyODcxNjAsImV4cCI6MjA5NTg2MzE2MH0.0x5VPc8HCE6TlsdnNC0d7aV3B1fZUgldVwOl2w3xeeg'
};
